### ISSUE TITLE
VF mastering

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/robotoslab#5]
Roboto Slab currently exists as 4 separate ufo sources: Thin, Light, Regular, and Bold. Their relationship is not strictly linear, as generating the same fonts from the two extremes, Thin and Bold, results in discrepancies on Regular and Light. When adding Regular in as a master the design has discrepancies that are much more subtle on the Light, and Nonexistent on the Regular.

These discrepancies are minimized when adding the Regular in as an intermediate third master but are still present. While I think that it would be nice to have the VF match 100% to the static fonts, I believe it will make for a more manageable source file (and smaller VF) to use Thin, Regular, and Bold for the mastering. However, if the differences are determined to be too large, then Light can be added in as a 4th master at the expense of file size.

Here is a comparison of the ttf generated from the original Light UFO as compared to the ttf generated as an instance between the Thin and Regular masters:
<img width="909" alt="screen shot 2018-07-16 at 11 38 59 am" src="https://user-images.githubusercontent.com/35570153/42768213-ea999a72-88ec-11e8-898b-5a8a7f2d854c.png">
[View on GF Regressions](http://gf-regression.com/compare/32fa8fb7-2bed-48f1-8ac2-d24876b77f1e)

**Comment by mjlagattuta** [comment]
[Here](http://gf-regression.com/compare/6ee86adb-59af-4707-8dfc-96cfaaa7f675) is the regressions page comparing current edits to those hosted on fonts.google.com

**Comment by davelab6** [comment]
> it will make for a more manageable source file (and smaller VF) to use Thin, Regular, and Bold for the mastering

I think this is fine :)
