### ISSUE TITLE
Edits to match Roboto’s 2014 update

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/robotoslab#6]
Some of the major revisions to Roboto (from 2014) have not yet made their way into Roboto Slab. The most obvious ones being the structure of the /R, /K, and /k, but also include rounder forms and less extreme flat portions in round glyphs. This is most noticeable in the smallcaps of Roboto Slab which do not match the capitals.

These modifications, while significantly changing the appearance of Roboto Slab, would make it more harmonious with Roboto and are additionally more consistent with the existing internal grammar of Roboto Slab, which is of the same skeletal structure as Roboto.

Roboto Slab edits and originals as compared to Roboto's new and old constructions:
<img width="1006" alt="screen shot 2018-07-16 at 10 23 58 am" src="https://user-images.githubusercontent.com/35570153/42768668-292733b6-88ee-11e8-84d9-f24498c2d01d.png">
<img width="880" alt="screen shot 2018-07-16 at 10 26 11 am" src="https://user-images.githubusercontent.com/35570153/42768669-2948936c-88ee-11e8-98a1-8eb79e7e96a2.png">

**Comment by davelab6** [comment]
> Some of the major revisions to Roboto (from 2014) have not yet made their way into Roboto Slab

Right, because Roboto Slab itself wasn't updated since before 2014. 

It will be great to keep them in sync! :)
