### ISSUE TITLE
Parity with Roboto’s weights

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/robotoslab#7]
Since Roboto and Roboto Slab are under one superfamily, I think it would make sense for them to be available in the same weights(Added weights noted below). Medium falls between masters and would be an instance. To get Roboto Slab Black an additinal master is needed. In this case extrapolation actually works quite well and yields a result that needs minimal correction to be used as a master.

Added weights would mean 6 matching weights to Roboto:
<img width="901" alt="screen shot 2018-07-16 at 12 02 15 pm" src="https://user-images.githubusercontent.com/35570153/42769419-1a604cd0-88f0-11e8-9704-587c844354fc.png">

Sample of the extrapolated Black with minor corrections on a few glyphs:
<img width="982" alt="screen shot 2018-07-16 at 12 00 10 pm" src="https://user-images.githubusercontent.com/35570153/42769311-d3e69b60-88ef-11e8-902e-f7266169cb51.png">

File size impacts: 
1 static ttf ≈ 170kB
3-master VF ≈ 220/230kB
4-master VF ≈  275kB 
(vf file sizes without VTT hinting)

**Comment by davelab6** [comment]
> Since Roboto and Roboto Slab are under one superfamily, I think it would make sense for them to be available in the same weights

I agree. 

Perhaps you can still do 3 masters, Thin Regular Black?

**Comment by mjlagattuta** [comment]
Yep, changes are very subtle and some improvements on /uni0423 with longer inner serifs and /Thorn with a bit more space between the bowl and serifs.

Spacing shifts by a couple of font units and there are no significant changes to color, So I believe we are good on this front as well

I will move forward with the 3 masters as Thin, Regular, and Black

**Comment by davelab6** [comment]
Sounds good, thanks!
