### ISSUE TITLE
Metrics and Kerning Inconsistencies

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/robotoslab#8]
I have been encountering numerous metrics related issues with Roboto Slab.

First are a few inconsistencies on sidebearings like with the /H 81, 81 .versus the /I 120, 120
Neither glyph's sidebearings correspond to the original ttf which is fine since there were unpublished edits which I am assuming modified spacing a bit, but this is a large 30 unit between sidebearings that should be very similar if not identical.

Proposed Solution: Modify metrics on glyphs (via metrics keys) with extreme deviations from the metrics of identical shapes 

---

Mark alignment is problematic across the board in the source ufos (the unpublished update). On top of this, automatic alignment of components on composite glyphs produce the wrong width and sidebearings, which in turn causes collisions, this is due to using noncombining marks as components rather than combining marks

Proposed Solution: The ideal solution in terms of structuring a good maintainable source file would be to set up glyphs with anchors and combining marks. this would mean making all noncombining marks use a component of the corresponding combining mark and then use the combining marks in the composite glyphs to enable automatic alignment. This would be fine without anchors, but I would argue that a proper anchor setup is more manageable than manually aligning and checking all components in all composites

---

Overall these inconsistencies mean that very little will match up on GF regressions

@davelab6 I did not want to mess with metrics and kerning so that updates will not deviate drastically from what is currently being served, but they seem necessary. What are your thoughts on how to move forward?

**Comment by davelab6** [comment]
> Modify metrics on glyphs (via metrics keys) with extreme deviations from the metrics of identical shapes

Yes, any quality improvements like this are welcome! :)

> set up glyphs with anchors and combining marks

Yes, totally renovating the font data to meet modern standards is also very welcome - should reduce filesize too! :)

> Overall these inconsistencies mean that very little will match up on GF regressions

That's fine; the purpose of the GFR tool is to be totally conscious about what we are changing and why. When we are improving the quality, some people may grumble that their layouts changed and they have to adjust them, but overall the quality is better for readers and for the long term.
